name: bw_utils
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.5-0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
